### ISSUE TITLE
`emailAddress`, `phoneNumber`, and `list` do not handle variables correctly

### ISSUE THREAD

**Issue by mikeogezi** [electrikmilk/cherri#36] opened 2023-12-06 02:02 UTC
**Describe the bug**
When `emailAddress`, `phoneNumber`, or `list` are used with a variable the produced Shortcut treats the variable as some sort of literal.

**To Reproduce**
```ruby
@e = "mike@example.com"
emailAddress(e)
```

**Debug output**
_The program compiles successfully, but here's an image of what happens_

<img width="631" alt="Screenshot 2023-12-05 at 6 57 53 PM" src="https://github.com/electrikmilk/cherri/assets/10839579/60428742-641b-4bee-8f41-dd1cc8ccea44">

**Expected behavior**

<img width="636" alt="Screenshot 2023-12-05 at 6 58 10 PM" src="https://github.com/electrikmilk/cherri/assets/10839579/c311409b-525e-410f-a280-b28f6014aa26">

**Screenshots**
_See above_

**Version Information (please complete the following information):**
 - macOS version (run `uname -a`): Darwin Michaels-MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0: Fri Oct 13 09:28:08 PDT 2023; root:xnu-10002.60.54~14/RELEASE_ARM64_T8112 arm64
 - Golang version (run `go version`): go version go1.21.4 darwin/arm64

**Comment by electrikmilk** [comment] 2023-12-09 02:39
This was caused by these actions accepting multiple values, and when they were implemented variables were not considered in the case of `list()`, but `emailAddress()` and `phoneNumber()` have a specific data structure for contact values, otherwise they allow their parameter to have a variable value, but not inline, and also only one value rather than multiple.

**Thanks for catching this!**

This is now fixed by [5b08264](https://github.com/electrikmilk/cherri/commit/5b08264adfcbb2f80f98fddea7f60ae117c86e42).

**Closed by electrikmilk** 2023-12-09 02:39 UTC
Labels: bug

**Comment by electrikmilk** [comment] 2023-12-09 02:40
`list()` also only allows string values and I'm not sure if maybe at the time I was confused how it would allow for inline variables as they did not work right away. This was because you need to give an item type, which is strange.
